---
# Should match on all of the the cmd line parameters
kernel_cmdline_regex: "{{ '(' ~ kernel_cmdline | select() | map('regex_escape') | list | join('|') ~ ')' }}" # noqa var-naming[no-role-prefix]

kernel_cmdline_sorted: "{{ kernel_cmdline | sort }}" # noqa var-naming[no-role-prefix]

# Should match on all of the the cmd line parameters that we want to remove
kernel_cmdline_remove_regex: "{{ '(' ~ kernel_cmdline_remove | join('|') ~ ')' }}" # noqa var-naming[no-role-prefix]
# same but for the grub_cmdline_linux and tnot the grub_cmdline_linux_default
kernel_cmdline_nondefault_remove_regex: "{{ '(' ~ kernel_cmdline_nondefault_remove | join('|') ~ ')' }}" # noqa var-naming[no-role-prefix]